penumbra-zone/jmt

src/hash/mod.rs, src/mock_tree_store.rs
Exposes the `define_hasher` macro and fixes the method signature of `write_node_batch`
=> Jmt key enum support

src/lib.rs, src/types/proof.rs, src/types/proof/definition.rs
We didn't include these when reorganizing the crate API.
=> Export merkle proof types

Cargo.toml, src/ics23_impl.rs, src/lib.rs
This doesn't implement non-existence proofs, and that implementation might
require further refinement of the proofspec in (our fork of) the ICS23 crate.
ICS23 provides a generic mechanism for non-existence proofs, which might be
different from the JMT's own mechanism.
=> Initial ICS23 existence proofs implementation.

Cargo.toml, src/ics23_impl.rs, src/lib.rs
Couple tests failing here, pending the corresponding `ics23` updates
=> Remove prefixes for KeyHash and ValueHash

Cargo.toml, src/lib.rs
This is useful because it allows the key bytes to be crossreferenced with the
key hash that appears in future tracing output.
=> Add tracing output to the KeyHash's From impl.

src/overlay.rs
The current code makes it difficult to use, because the associated constant is
only defined for `WriteOverlay<R>` where `R` satisfies the trait bounds.
Instead, lifting it into its own impl allows it to be used for any `R`, which
is better, because the value doesn't depend on `R`.
=> Lift the WriteOverlay::PRE_GENESIS_VERSION associated constant into its own impl block.

src/node_type.rs, src/tree.rs
Resolves #44, making `get` save work by never doing any of the effort required to generate a proof which it will then throw away. I implemented this without particularly deep knowledge of how the JMT works, by starting with a copy of `get_with_proof` (called `get_without_proof`) and removing the output proof, then correcting errors that resulted from that, then following "unused variable" warnings, and proceeding into subroutines to generate less-effortful versions of them as necessary also.
It would be nice to have a test which shows that `tree.get_with_proof(key).0 == tree.get(key)` for all `key`. We could use proptest for this, or we could feel satisfied by a couple of unit tests? What do you think @aubrika?
=> Make `get` more efficient by never generating proofs

src/iterator.rs, src/mock.rs, src/node_type.rs, src/reader.rs, src/restore.rs, src/tests/helper.rs, src/tests/jellyfish_merkle.rs, src/tests/node_type.rs, src/tests/tree_cache.rs, src/tree.rs, src/tree_cache.rs, src/types.rs, src/types/nibble.rs, src/writer.rs
This PR removes the `value` field from `LeafNode`, allowing values to be handled separately in the underlying data store. This allows very efficent `get` operations, since the tree no longer needs to be traversed in order to find the value of a given key. The tree is still traversed if a proof is requested.
=> Separate LeafNodes from values

src/tree/ics23_impl.rs
This PR updates one of the field names in the struct created by `ics23_spec()` from `prehash_compare_key` to `prehash_key_before_comparison`
=> Bug fix: incorrect field name in ics23_spec

src/tree.rs
The previous link was broken as the `TreeReader` trait is now under `storage`.
=> Fix broken TreeReader doc link

src/node_type.rs, src/writer.rs
Jmt already derives serde for most types, but a few were missing. This PR adds derives on the missing types.
=> Add missing serde derives

.github/workflows/rust.yaml
After merge of https://github.com/penumbra-zone/jmt/pull/92, we observed a CI test failure on the `main` branch [0]. We couldn't reproduce locally, and a subsequent CI re-run passed [1], so we're chalking it up to non-determinism caused by our use of proptest. When proptest finds a failure, it generates text files that can be version-controlled to isolate that input in the future. Unfortunately, we lose that info in the CI runs; this commit is an attempt to change that, so we can inspect a failing CI run in the future and reproduce the failing test locally to understand the conditions better.
[0] https://github.com/penumbra-zone/jmt/actions/runs/4950336820/attempts/1
[1] https://github.com/penumbra-zone/jmt/actions/runs/4950336820
=> ci: emit proptest regressions on test failures

Cargo.toml, src/lib.rs, src/node_type.rs, src/restore.rs, src/tests/helper.rs, src/tests/jellyfish_merkle.rs, src/tests/node_type.rs, src/tests/restore.rs, src/tests/tree_cache.rs, src/tree.rs, src/tree_cache.rs, src/types/proof.rs, src/types/proof/definition.rs, src/types/proof/proptest_proof.rs
A previous PR made the JMT generic over hash function. At that time, however, we did not implement any tests using a different hasher. As a result, we didn't catch that the implementations of `InternalNode` and `LeafNode` still had hidden `sha2` invocations hardcoded. Oops! This PR fixes those issues, and adds some tests using `blake3`.
In addition, the previous work had not modified the various proof types supported by the JMT (`SparseMerkleProof`, `SparseMerkleRangeProof`, etc.). This PR also makes those types generic over hash.
Finally, the PR makes a few small tweaks related to type inference and trait bounds - notably removing the `PhantomHasher` type and using `PhantomData` in its place. 
1. Manually generate test vectors for `blake3`
2. Add `blake3` versions of remaining …
=> Remove HardCoded sha2; Add Blake3 Tests

Cargo.toml
This PR switches the jmt to `ics23@0.11` and prepares release `v0.9.0`
=> jmt: use latest ics23 spec

Cargo.toml, src/lib.rs, src/tree.rs, src/tree_cache.rs
Context: 
Performing offline state migrations without incrementing the tree version: https://github.com/penumbra-zone/penumbra/issues/3506.
This PR adds:
- `TreeCache::new_overwrite` gated behind a `migration` feature. This method instantiate a `TreeCache` against a root node key defined at the current version of the tree (rather than the previous one).
- `JellyfishMerkleTree::append_value_set` gated behind a `migration` feature. This method appends key/values against the current tree (using `new_overwrite`) and return the corresponding node batch.
We validated this approach in https://github.com/penumbra-zone/penumbra/issues/4053
=> jmt: allow incremental tree overwrites for a given version

Cargo.toml
This prepare release `0.10` of the crate.
=> jmt: bump version to `0.10`

src/tree/ics23_impl.rs
This PR adds a proptest setup that exercises the bounding path logic used to generate ics23 non-existence proofs.
**Context**
In #100, we fixed a bug located deep in the logic determining the adjacency of two subtrees in the jmt. As part of review, it was pointed out that writing property tests that exercise the different "types" of nonexistence setups/adjacency would have high ROI. As a result, we filed #104 and outlined a testing strategy in [this comment](https://github.com/penumbra-zone/jmt/issues/104#issuecomment-2024337306).
**Proptest strategy**
```rust
/// Assert that the Ics23 bonding path calculations are correct.
/// To achieve this, the uses a strategy that consists in:
/// 1. generating a sorted vector of key preimages
/// 2. instantiating a JMT over a `TransparentHasher`
/// …
```
=> tree(ics23): add bounding path calculation proptests

src/types/proof/definition.rs
`borsh` changed their macro logic for bound inference in their `1.0` release. Unforunatley, the change causes `borsh` to infer spurious bounds on generic types in some cases. This PR removes the unnecessary bounds on types which are generic over a `Hasher`.
=> Remove spurious Hasher: BorshSerialize + BorshDeserialize bounds

src/tree.rs
This tiny PR makes the root hash of an empty tree an associated constant.
=> Add const for empty root

Cargo.toml
This prepare release `v0.12.0`, including #124
=> jmt: prepare `v0.12.0`
